name: crt1d-dev
channels:
  - conda-forge
dependencies:
  - python=3.7
  # used by crt1d
  - numpy
  - scipy
  - matplotlib
  - xarray
  - pandas
  # for docs
  - sphinx
  - nbsphinx
  - jupytext
  - notebook
  # dev tools
  - pylint
