name: crt1d-dev
channels:
  - conda-forge
dependencies:
  - python=3.7
  # used by crt1d
  - numpy
  - scipy
  - matplotlib
  - xarray
  - pandas
  # for docs
  - sphinx
  - nbsphinx
  - jupytext
  - notebook
  - sphinxcontrib-bibtex
  - myst-parser  # they recommend Conda install over Pip
  - pip  # otherwise conda nags
  - pip:
    - sphinx-rtd-theme
    - '-e .'
    - SolarUtils  # run SPCTRAL2 to get more solar spectra
    - prosail  # run PROSPECT to get more leaf spectra; has numba as a dep
  # dev tools
  - pylint
  - rope
