name: crt1d-dev
channels:
  - conda-forge
dependencies:
  - python=3.7
  #
  # used by crt1d (prefer Conda versions though)
  - numpy
  - scipy
  - matplotlib
  - xarray
  - pandas
  #
  # for docs
  - sphinx
  - jupytext
  - notebook
  - pip  # otherwise conda nags
  - pip:
    - '-e .'
    - sphinx-book-theme
    - sphinx-autoapi
    - myst-nb
    - sphinxcontrib-bibtex
    # TODO: should add the below to an extras_require for the package
    - SolarUtils  # run SPCTRAL2 to get more solar spectra
    - prosail  # run PROSPECT to get more leaf spectra; has numba as a dep
  #
  # dev tools
  - pylint
  - rope
